-- SET statement_timeout = 0;

-- CREATE TABLE transactions (
--     id VARCHAR DEFAULT gen_random_uuid() PRIMARY KEY,
--     user_id VARCHAR NOT NULL,
--     product_id VARCHAR NOT NULL,
--     qr_code_id VARCHAR NOT NULL,
--     price_type VARCHAR NOT NULL,
--     price INT NOT NULL,
--     amount INT NOT NULL,
--     total_price INT NOT NULL,
--     status INT NOT NULL,
--     slip_image VARCHAR NOT NULL
-- );
